
# 配置Eureka信息
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server # eureka实例的主机名
  client:
    register-with-eureka: false #不把自己注册到eureka上
    fetch-registry: false #不从eureka上来获取服务到注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

